#!/usr/bin/env node
const path = require('path')
const exec = require('./exec')

function demoModule (cwd) {
  const rootDir = path.resolve(__dirname, '../')

  // webpack-dev-server arguments.
  const args = [
    '--open',
    `--config ${rootDir}/webpack.demo.config.js`,
    `--context ${cwd}/demo`
  ]

  exec(`webpack-dev-server ${args.join(' ')}`, {
    cwd: rootDir,
    env: {
      NODE_ENV: 'test',
      BABEL_ENV: 'es'
    }
  })
}

// Are we running this directly?
if (process.argv[0].match(/bin\/node$/) && process.argv[1].match(/demo-module$/)) {
  demoModule(process.cwd())
}

module.exports = demoModule
